name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Enable Corepack and setup Yarn
      run: |
        corepack enable
        corepack prepare yarn@4.0.0 --activate
        yarn --version
      
    - name: Install dependencies
      run: yarn install --immutable
      
    - name: Debug workspace structure
      run: |
        echo "=== Workspace info ==="
        yarn workspaces list
        echo "=== Prompts service package.json ==="
        cat packages/trip-bundle-prompts-service/package.json
        echo "=== PWA package.json ==="
        cat packages/trip-bundle-pwa/package.json
      
    - name: Build prompts service first
      run: |
        echo "=== Building prompts service ==="
        yarn workspace trip-bundle-prompts-service build
        echo "=== Checking dist folder ==="
        ls -la packages/trip-bundle-prompts-service/dist/
        echo "=== Checking if types are generated ==="
        ls -la packages/trip-bundle-prompts-service/dist/*.d.ts
      
    - name: Type check
      run: yarn workspaces foreach --all run type-check || true
      
    - name: Lint
      run: yarn workspaces foreach --all run lint || true
      
    - name: Build remaining packages
      run: |
        yarn workspace trip-bundle-playground build
        yarn workspace trip-bundle-pwa build
      
    - name: Test
      run: yarn workspaces foreach --all run test || echo "No tests configured"

  build-pwa:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Enable Corepack and setup Yarn
      run: |
        corepack enable
        corepack prepare yarn@4.0.0 --activate
        yarn --version
      
    - name: Install dependencies
      run: yarn install --immutable
      
    - name: Build prompts service first
      run: yarn workspace trip-bundle-prompts-service build
      
    - name: Create mock environment file
      run: |
        cd packages/trip-bundle-pwa
        echo "# Mock mode - no API keys needed" > .env
        echo "VITE_MOCK=true" >> .env
        echo "GITHUB_PAGES=true" >> .env
      
    - name: Build PWA (Mock Mode)
      run: |
        cd packages/trip-bundle-pwa
        VITE_MOCK=true GITHUB_PAGES=true yarn build
      
    - name: Create builds directory and copy mock build
      run: |
        cd packages/trip-bundle-pwa
        mkdir -p builds/mock
        cp -r dist/* builds/mock/
      
    - name: Build PWA (Prod)
      run: yarn workspace trip-bundle-pwa build:prod
      
    - name: Copy prod build to builds directory
      run: |
        cd packages/trip-bundle-pwa
        mkdir -p builds/prod
        cp -r dist/* builds/prod/
      
    - name: Verify PWA files
      run: |
        cd packages/trip-bundle-pwa
        echo "Checking if pwa.html was created:"
        ls -la dist/pwa.html || echo "pwa.html not found!"
        echo "Checking dist contents:"
        ls -la dist/
        echo "Checking builds directory:"
        ls -la builds/
        echo "First few lines of pwa.html:"
        head -10 dist/pwa.html || echo "Could not read pwa.html"
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      if: github.ref == 'refs/heads/main'
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pwa-builds
        path: packages/trip-bundle-pwa/builds/
        
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      if: github.ref == 'refs/heads/main'
      with:
        path: './packages/trip-bundle-pwa/dist'

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-pwa
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
