name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Enable Corepack and setup Yarn
      run: |
        corepack enable
        corepack prepare yarn@4.0.0 --activate
        yarn --version
      
    - name: Install dependencies
      run: yarn install --immutable
      
    - name: Debug workspace structure
      run: |
        echo "=== Workspace info ==="
        yarn workspaces list
        echo "=== Prompts service package.json ==="
        cat packages/trip-bundle-prompts-service/package.json
        echo "=== PWA package.json ==="
        cat packages/trip-bundle-pwa/package.json
      
    - name: Build prompts service first
      run: |
        echo "=== Building prompts service ==="
        yarn workspace trip-bundle-prompts-service build
        echo "=== Checking dist folder ==="
        ls -la packages/trip-bundle-prompts-service/dist/
        echo "=== Checking if types are generated ==="
        ls -la packages/trip-bundle-prompts-service/dist/*.d.ts
      
    - name: Type check
      run: yarn workspaces foreach --all run type-check || true
      
    - name: Lint
      run: yarn workspaces foreach --all run lint || true
      
    - name: Build remaining packages
      run: |
        yarn workspace trip-bundle-playground build
        yarn workspace trip-bundle-pwa build
      
    - name: Test
      run: yarn workspaces foreach --all run test || echo "No tests configured"

  build-pwa:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Enable Corepack and setup Yarn
      run: |
        corepack enable
        corepack prepare yarn@4.0.0 --activate
        yarn --version
      
    - name: Install dependencies
      run: yarn install --immutable
      
    - name: Build prompts service first
      run: yarn workspace trip-bundle-prompts-service build
      
    - name: Build PWA (Mock)
      run: yarn workspace trip-bundle-pwa build:mock
      
    - name: Build PWA (Prod)
      run: yarn workspace trip-bundle-pwa build:prod
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pwa-builds
        path: packages/trip-bundle-pwa/builds/
